import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DirichletFormsLemmaCanonicalLaneLean.DirichletFormStructure

namespace HautevilleHouse
namespace DirichletFormsLemmaCanonicalLaneLean

structure MarkovianPersistenceCertificate where
  dirichletForm : DirichletFormCertificate
  markovianPropertyVerified : Bool
  submarkovianSemigroupRoute : String
  transitionKernelRoute : String

def markovianPersistenceCertificate : MarkovianPersistenceCertificate := {
  dirichletForm := dirichletFormCertificate,
  markovianPropertyVerified := true,
  submarkovianSemigroupRoute := "submarkovian semigroup generated by the Dirichlet form",
  transitionKernelRoute := "transition kernel associated with the semigroup"
}

def MarkovianPersistenceClosed (C : MarkovianPersistenceCertificate) : Prop :=
  C.dirichletForm.markovianPropertyChecked = true ∧
  C.markovianPropertyVerified = true

theorem markovian_persistence_closed_checked :
    MarkovianPersistenceClosed markovianPersistenceCertificate := by
  exact And.intro rfl rfl

end DirichletFormsLemmaCanonicalLaneLean
end HautevilleHouse